### ISSUE TITLE
About the training of input embedding.

### ISSUE THREAD

**Issue by TousakaNagio** [adobe-research/custom-diffusion#52]
In the paper "Multi-Concept Customization of Text-to-Image Diffusion," it is stated that only the target token "new1" or V* was tuned. However, upon reviewing the code in diffuser_training.py, it appears that the entire embedding was optimized. Can you clarify if this is accurate? Thank you for your response.

**Comment by nupurkmr9** [comment]
Hi, in the case of diffusers based code, we keep all embeddings trainable but manually set the gradient of all other embeddings except <new1> token (denoted as V* in the paper) to 0 [here](https://github.com/adobe-research/custom-diffusion/blob/32786fb186f105de794155f96878664bc4d2e84d/src/diffusers_training.py#L1013). 
Thanks!

**Comment by TousakaNagio** [comment]
I got it. Thank you for your respond!

**Comment by TousakaNagio** [comment]
Another question. Would you please indicate the code which corresponding to [here](https://github.com/adobe-research/custom-diffusion/blob/32786fb186f105de794155f96878664bc4d2e84d/src/diffusers_training.py#L1013) in train.py/custom_modules.py/model.py? Thanks!

**Comment by nupurkmr9** [comment]
In the case of model.py, I simply detached all other embeddings [here](https://github.com/adobe-research/custom-diffusion/blob/4e27bfcc3ee0597784b730076b4a87a1b3c6e348/src/custom_modules.py#L298) instead of zeroing out the gradients. 
We can also zero out the gradients by defining a callback function which I tried in one of our new projects [here](https://github.com/nupurkmr9/concept-ablation/blob/00e8da0e21819cede13b143ce33f4565fab7b68c/train.py#L754)

**Comment by TousakaNagio** [comment]
Thank you for your detailed explanation. It has been very helpful for my research.
