### ISSUE TITLE
Huge gap text-alignment score for textual inversion (original paper and your replication)

### ISSUE THREAD

**Issue by studying910** [adobe-research/custom-diffusion#56]
Hi, congratulations on this great work! :)

I found that in the original paper of textual inversion, their clip score of text alignment is around 0.26.

However, in your appendix, you replicate their methods with much better results (around 0.65).

I am wondering what is the difference between this two results.

Are you using different methods to calculate the clip score or just I misunderstood it?

**Comment by nupurkmr9** [comment]
Hi, we followed the official [CLIP Score](https://github.com/jmhessel/clipscore) to measure text alignment. In their code they multiply the dot product with a scale factor of 0.25 to bring the score in the scale of 0-1 and have a discussion regarding it in the [paper](https://arxiv.org/pdf/2104.08718.pdf). 
Since, we used the same metric across all methods, so the comparisons shouldn't be affected by the scaling.

Thanks.

**Comment by studying910** [comment]
> 

It makes a sense.
However, when I compare the Image-image similarity using CLIPScore between your results and textual inversion, it turns out that your results are in the same order of magnitude, but they just use a scale factor of 1.0.

I am not sure if I understand it, but:
Are you using a scale factor of 1.0 to compute the image2image similarity and
a scale factor of 2.5 to compute the image2text similarity?

**Comment by nupurkmr9** [comment]
Yes, your undertaking is correct. Sorry for the confusion. 
For image2image similarity, a scale factor of 1.0 is used. For text2image similarity a scale factor of 2.5 is used following CLIPScore. 
Thanks.

**Comment by studying910** [comment]
> Yes, your undertaking is correct. Sorry for the confusion. For image2image similarity, a scale factor of 1.0 is used. For text2image similarity a scale factor of 2.5 is used following CLIPScore. Thanks.

Thanks again for your patience. Now all my doubts within this paper have been solved. 
I think I should close this issue :)
